### ISSUE TITLE
Expand functionality of Scatter Plot (i) multiple hue columns and (ii) accept column

### ISSUE THREAD

**Issue by cudmore** [mapmanager/PyMapManager#18]
[scatter_plot_widget](https://github.com/mapmanager/PyMapManager/blob/cudmore-dev/pymapmanager/interface2/core/scatter_plot_widget.py#L388) in interface2/core/ should accept some additional parameters in __init__().

In turn the actual PyMapManager [scatter widget](https://github.com/mapmanager/PyMapManager/blob/cudmore-dev/pymapmanager/interface2/stackWidgets/pmmScatterPlotWidget.py#L20) should build the core scatter with some additional meaningful params.

In [scatter_plot_widget](https://github.com/mapmanager/PyMapManager/blob/cudmore-dev/pymapmanager/interface2/core/scatter_plot_widget.py#L388), __init__() should have signature like

```python
def __init__(self,
   df : pd.DataFrame,
   filterColumn : Optional[str] = None,
   acceptColumn : Optional[str] = None,
   hueColumnList: Optional[List[str]] = None):
   """
   Parameters
   ------------
   df : pd.DataFrame
      Pandas dataframe to plot scatter, one scatter point per row.
   filterColumn : str
      TODO: not sure what this was for?
   acceptColumn : str
      Column in df to treat as accept (values should be (True, False) or (1, 0)
   hueColumnList : list[str]
      A list of column names in df to allow displaying them as hue (color) in the scatter plot.
      Each hue column should be categorical.
   """
```

## New features

- if acceptColumn is not None, add a checkbox to turn 'show accept' on/off. When showing accept, always show accept=False with some noticeable color like 'white'.
- if hueColumnList is not None, make two popups.

    1. Entries are items from hueColumnList. Prepend an item 'None' to allow 'no hue', e.g. no coloring.
    2. Entries are unique() values in selected hue column (from the first popup). Prepend 'All' like in the current interface.

## Rational

Currently we only allow one hue (pmm is using segmentID). It would be good to have a number of possible hues like ['segmentID', 'userType']. Maybe more?

All specified hue columns should be categorical so we can make a small number of popup entries using unique().

**Comment by cudmore** [comment]
From @jtle00 

Hi Robert, I saw your github issue for the scatter plot. I had some confusion that I wanted clarification on regarding:

if hueColumnList is not None, make two popups.
- Entries are items from hueColumnList. Prepend an item 'None' to allow 'no hue', e.g. no coloring.
- Entries are unique() values in selected hue column (from the first popup). Prepend 'All' like in the current interface.
Perhaps it would be clearer if we used an example such as segmentID being the hueColumnList.

When you say popups are you referring to combo boxes?

For the first popup the items would be [0, 1, 2, 3, 4, None]. If we click None the plot is not colored at all. What would happen if we clicked 1? Would only items in segment 1 be colored?

For the second popup I am assuming this is the same as what is currently implemented. Where we have a combo box of [0, 1, 2, 3, 4, All]. So if we click on 1, only items within segment one are showed in the plot. If this is incorrect please let me know.

**Comment by cudmore** [comment]
“When you say popups are you referring to combo boxes?“

yes I mean QComboxBox.

“Perhaps it would be clearer if we used an example such as segmentID being the hueColumnList.”

Actually hueColumnList is always a List[str] or None. An example would be hueColumnList=[‘userType’, ‘segmentID’]

The first combobox would have items [‘None’, ‘userType’, ‘segmentID’]. When the user selects:
- ‘None’, the second QComboxBox would be set inactive and all colors in the scatter would be turned off.
- ‘segmentID’, the second QComboxBox would be populated with  [‘All’, df[‘segmentID’].unique()]
- ‘userType’, the second QComboBox would be populated with a list of items [‘All’, 0, 1, 2, .., 9] , e.g. [‘All’, range(10)]. This is an edge case where we know the possible range of user type. See below for more simple variation.

The second QComboBox will be repopulated with values each time a hue is selected in the first QComboBox. The second QComboBox is similar to what we have now, it is just not always [0,1,2,3,4,All].

Slight addition to above. For any selection in the first QComboBox, the second QComboBox always takes on items ['All', df[hueColStr].unique()] where hueColStr is str value from the first QComboBox.

**Comment by jtle00** [comment]
These functionalities have been implemented in the branch [oldPlotNewInterface2](https://github.com/mapmanager/PyMapManager/tree/oldPlotNewInterface2).
The branch is now up to date with these changes.

**Comment by jtle00** [comment]
It might be important to mention that the filterColumn argument was used to display a combo box of unique values within the given column that was specified. For example, in the first version of the widget, we used it for the roiTypes column. The user was then able to pick between the choices of spineROI, ControlPnts, globalPivot, and pivotPnts within the combo box. The widget would then plot only the values from the data frame that matched those types. However, now that the given dataframe only deals with spineROI points this may no longer be necessary. Would you want me to remove this feature?

**Comment by cudmore** [comment]
Yes, I would just remove or comment out the code for `filterColumn` and the combo box for unique values within the filter column. As you said, this is for different roiTypes and for now our core backend just has spineRoi and thus no need for the filter on roi type!

**Comment by jtle00** [comment]
Sure thing. I have commented this out in my `johnson-dev` branch.
