### ISSUE TITLE
Add an 'Annotations' options to show/hide all annotations in StackToolBar()

### ISSUE THREAD

**Issue by cudmore** [mapmanager/PyMapManager#21]
## Feature Request

Add a new option to the combo box popup to hide/show all annotations.

In `class StackToolBar()`, add an `"Annotations"` item to the QComboBox `plotMenuList`.

```
plotMenuList = ["Spines", "Center Line", "Radius Lines", "Labels", "Image"]
```

When `Annotations` is `True` we show all annotations including (Spines, Center Line, Radius Lines, Labels)

When `Annotations` is `False` we hide all annotations including (Spines, Center Line, Radius Lines, Labels).

**Comment by jtle00** [comment]
Implemented within johnson-dev branch as of 10/24/24
