### ISSUE TITLE
Cleaning up the GUI a bit

### ISSUE THREAD

**Issue by cudmore** [mapmanager/PyMapManager#22]
In the stack widget main window, we have a few GUI widgets that need to be merged/removed.

There is the top toolbar that has a right click, looks like this:

![image](https://github.com/user-attachments/assets/790153e6-4df8-4985-a60c-2f371b384e80)

Basically, we can **remove** this right-click (context menu) because all functionality are in other parts like "Plots" combobox and "View" menu.

[x] Points, it is already in the "Plots" combobox
[x] Lines, it is already in the "Plots" combobox
[x] Histogram, it is already in the "View" menu
[] Plugins, needs to be added to the "View" menu
[x] Stack Toolbar, already in the "View" menu as "top toolbar" ... can we get a better name for this???
[] Status Toolbar, needs to be added to the "View" menu

**Comment by jtle00** [comment]
This issue has been resolved in branch: **johnson-dev**.
